### ISSUE TITLE
What the difference to redmine_issue_history ?

### ISSUE THREAD

**Issue by cforce** [tastapod/redmine_issue_history_tabs#1]
https://github.com/freedayko/redmine_issue_history

Can you provide screenshots and some description - tx!

**Comment by tastapod** [comment]
I haven't looked at redmine_issue_history. I came across the redmine_issue_history_tabs plugin on the Redmine wiki, and just copied the code in from a [Google Code](http://code.google.com/p/kosz-redmine-tools/) repository so I could hack on it to work with Redmine 1.1.0 :)
