### ISSUE TITLE
Missing private comments (redmine 2.2.1)

### ISSUE THREAD

**Issue by cforce** [tastapod/redmine_issue_history_tabs#10]
The plugin is not compatible with redmine 2.2, because the private comments which are shown in All tab are not shown in "comments" tab. Maybe the tag id names changed.

**Comment by cforce** [comment]
Can you confirm or not? Any feedback?

**Comment by tastapod** [comment]
Hi @cforce. I'm not doing any active development on this repo, but I'm accepting pull requests if you want to make any changes. Also @NEXSTEP has an actively-maintained fork, so if s/he offers me any pull requests I'll happily merge them in.

**Comment by cforce** [comment]
Can u write down we complete link, because i can't find any repo from NEXSTEP for this plugin.

**Comment by cforce** [comment]
Where is the repo of Nexstep, please help me out?

**Comment by cforce** [comment]
I saw you just pushed some chnages which show comments now but in "All" tab instead of "Comments" tab.
Sure private messages shall be showed only in comments tab if allowed to see it.
