### ISSUE TITLE
Editing a Comment doesn't work

### ISSUE THREAD

**Issue by pauleil** [tastapod/redmine_issue_history_tabs#4]
If you click Edit while in Comment view, nothing happens. To edit a comment, user needs to switch to the All tab.
Using Redmine 1.1.2

**Comment by tastapod** [comment]
Thanks for letting me know. I'll take a look.

**Comment by pauleil** [comment]
Thank you. Have you had a chance to take a look?

**Comment by tastapod** [comment]
I doubt I'll get to look at this for a while. If you manage to figure out
what's going on I'll happily accept a pull request.

**Comment by pauleil** [comment]
Unfortunately, I don't know anything about Redmine plugin coding.
Do you have any ideas on what the reason may be? Has the event handler name changed in the newest Redmine?

**Comment by ghost** [comment]
+1
This plugin looks awesome.  But there is no way I could implement it in a workgroup environment with this bug still in it :(

**Comment by ghost** [comment]
I tested this out with Redmine 1.2.2.  When you click the Edit icon under the Comments tab, it actually does open the Edit window.  But instead of opening it on the Comments tab, it opens it on the All tab, which is why you don't see anything!

**Comment by danmunn** [comment]
Problem stems from RJS page.insert_html only allowing an ID; plugin renders 2 elements with same ID (IDs should be unique) and thus the first is selected regardless of visual intent. Additional approach would be to override the journal helper to provide contextual id suffix/prefix and then overriding the edit and update rjs files for journal. That being said, have mixed up the approach of another user on different reported issue and have forked the codebase, removing the_history_comments.rhtml and _history_all.rhtml - and using _history.rhtml (or .html.erb in redmine 1.4/2.0) to allow default rendering. Included a JS file which hooks onto generated tab buttons which in-turn allow for journal entries with certain classes based on default implementation.

**Comment by tastapod** [comment]
Fixed by pull request #7
