### ISSUE TITLE
The Comments tab does not refresh

### ISSUE THREAD

**Issue by ghost** [tastapod/redmine_issue_history_tabs#5]
Edit a comment on the All tab, submit it and then switch to the Comments tab.  The edit does not show up.  Only once you force refresh the web page does this comment appear.

So it appears that the problem is just that Comments does not automatically refresh when changes are made to All.

**Comment by tastapod** [comment]
Hi Adam. If you manage to fix this I'll be happy to accept a pull request.

**Comment by ghost** [comment]
I would love to.  Unfortunately, I know absolutely nothing about RoR or Redmine plugin development :(

**Comment by cforce** [comment]
We fixed it. I will try to find time to fork and pull tomorrow

**Comment by cforce** [comment]
..Push :)

**Comment by ghost** [comment]
Terence, you are awesome!  I can't wait to check this out.

Best,
-Adam

**Comment by cforce** [comment]
Aha,, i complety rewrote it to js.

Not sure i extracted that corretly to redmine plugin, cause  hacked that in views directly.

Well, next week i can test more and localize maybe.

https://github.com/cforce/redmine_issue_tabs

**Comment by tastapod** [comment]
Nice. Do you want me to merge that back in or are you interested in taking over maintenance of this plugin?

**Comment by cforce** [comment]
If you gonna improve that too, fork it.
I

**Comment by tastapod** [comment]
Fixed by Pull request #7
